"""
Alembic Script Template
Mako template for generating migration files
"""

"""Phase 6A and 6B: Add mock test v2 and career intelligence tables

Revision ID: 3725a436c82a
Revises: ee977a322e90
Create Date: 2026-01-24 21:32:03.648318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3725a436c82a'
down_revision = 'ee977a322e90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quotes_id'), 'daily_quotes', ['id'], unique=False)
    op.create_table('ai_coaching_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('weekly_focus', sa.JSON(), nullable=True),
    sa.Column('priority_topics', sa.JSON(), nullable=True),
    sa.Column('this_week_goals', sa.JSON(), nullable=True),
    sa.Column('next_week_preview', sa.JSON(), nullable=True),
    sa.Column('last_week_progress', sa.Text(), nullable=True),
    sa.Column('strengths_identified', sa.JSON(), nullable=True),
    sa.Column('gaps_identified', sa.JSON(), nullable=True),
    sa.Column('study_plan', sa.Text(), nullable=True),
    sa.Column('resource_recommendations', sa.JSON(), nullable=True),
    sa.Column('practice_recommendations', sa.JSON(), nullable=True),
    sa.Column('encouragement_message', sa.Text(), nullable=True),
    sa.Column('milestone_celebration', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_coaching_sessions_id'), 'ai_coaching_sessions', ['id'], unique=False)
    op.create_table('career_dna_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('logical_ability', sa.Float(), nullable=False),
    sa.Column('problem_solving', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('learning_efficiency', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('improvement_areas', sa.JSON(), nullable=True),
    sa.Column('personality_type', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_role_id')
    )
    op.create_index(op.f('ix_career_dna_profiles_id'), 'career_dna_profiles', ['id'], unique=False)
    op.create_table('career_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('internship_readiness', sa.Float(), nullable=False),
    sa.Column('placement_readiness', sa.Float(), nullable=False),
    sa.Column('project_readiness', sa.Float(), nullable=False),
    sa.Column('estimated_days_to_internship', sa.Integer(), nullable=True),
    sa.Column('estimated_days_to_placement', sa.Integer(), nullable=True),
    sa.Column('best_fit_roles', sa.JSON(), nullable=True),
    sa.Column('predicted_salary_range', sa.String(), nullable=True),
    sa.Column('success_probability', sa.Float(), nullable=False),
    sa.Column('forecast_summary', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_forecasts_id'), 'career_forecasts', ['id'], unique=False)
    op.create_table('learning_velocity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('topics_per_week', sa.Float(), nullable=False),
    sa.Column('concepts_mastered_per_day', sa.Float(), nullable=False),
    sa.Column('average_retention_rate', sa.Float(), nullable=False),
    sa.Column('peak_learning_hours', sa.JSON(), nullable=True),
    sa.Column('best_learning_days', sa.JSON(), nullable=True),
    sa.Column('preferred_learning_mode', sa.String(), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_learning_hours', sa.Float(), nullable=False),
    sa.Column('velocity_trend', sa.String(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_velocity_id'), 'learning_velocity', ['id'], unique=False)
    op.create_table('mock_tests_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('topics_used', sa.JSON(), nullable=False),
    sa.Column('mcq_count', sa.Integer(), nullable=False),
    sa.Column('coding_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_v2_id'), 'mock_tests_v2', ['id'], unique=False)
    op.create_table('skill_graphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('skill_category', sa.String(), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('node_weight', sa.Float(), nullable=False),
    sa.Column('connections', sa.JSON(), nullable=True),
    sa.Column('first_encountered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_practiced', sa.DateTime(), nullable=True),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_graphs_id'), 'skill_graphs', ['id'], unique=False)
    op.create_table('user_performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('total_tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('best_score', sa.Float(), nullable=False),
    sa.Column('worst_score', sa.Float(), nullable=False),
    sa.Column('score_trend', sa.JSON(), nullable=True),
    sa.Column('accuracy_improvement', sa.Float(), nullable=False),
    sa.Column('strong_areas', sa.JSON(), nullable=True),
    sa.Column('weak_areas', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_role_id')
    )
    op.create_index(op.f('ix_user_performance_metrics_id'), 'user_performance_metrics', ['id'], unique=False)
    op.create_table('mock_test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('mcq_score', sa.Float(), nullable=False),
    sa.Column('coding_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('weak_topics', sa.JSON(), nullable=True),
    sa.Column('strong_topics', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('improvement_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['mock_tests_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_attempts_id'), 'mock_test_attempts', ['id'], unique=False)
    op.create_table('mock_test_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['mock_tests_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_questions_id'), 'mock_test_questions', ['id'], unique=False)
    op.create_table('coding_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('code_submitted', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=False),
    sa.Column('total_test_cases', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['mock_test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['mock_test_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_submissions_id'), 'coding_submissions', ['id'], unique=False)
    op.create_table('mock_test_section_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers', sa.Integer(), nullable=False),
    sa.Column('unanswered', sa.Integer(), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['mock_test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['mock_tests_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_section_scores_id'), 'mock_test_section_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_test_section_scores_id'), table_name='mock_test_section_scores')
    op.drop_table('mock_test_section_scores')
    op.drop_index(op.f('ix_coding_submissions_id'), table_name='coding_submissions')
    op.drop_table('coding_submissions')
    op.drop_index(op.f('ix_mock_test_questions_id'), table_name='mock_test_questions')
    op.drop_table('mock_test_questions')
    op.drop_index(op.f('ix_mock_test_attempts_id'), table_name='mock_test_attempts')
    op.drop_table('mock_test_attempts')
    op.drop_index(op.f('ix_user_performance_metrics_id'), table_name='user_performance_metrics')
    op.drop_table('user_performance_metrics')
    op.drop_index(op.f('ix_skill_graphs_id'), table_name='skill_graphs')
    op.drop_table('skill_graphs')
    op.drop_index(op.f('ix_mock_tests_v2_id'), table_name='mock_tests_v2')
    op.drop_table('mock_tests_v2')
    op.drop_index(op.f('ix_learning_velocity_id'), table_name='learning_velocity')
    op.drop_table('learning_velocity')
    op.drop_index(op.f('ix_career_forecasts_id'), table_name='career_forecasts')
    op.drop_table('career_forecasts')
    op.drop_index(op.f('ix_career_dna_profiles_id'), table_name='career_dna_profiles')
    op.drop_table('career_dna_profiles')
    op.drop_index(op.f('ix_ai_coaching_sessions_id'), table_name='ai_coaching_sessions')
    op.drop_table('ai_coaching_sessions')
    op.drop_index(op.f('ix_daily_quotes_id'), table_name='daily_quotes')
    op.drop_table('daily_quotes')
    # ### end Alembic commands ###
